---
- name: BUILD IMAGE
  hosts: ansible

  tasks:
  - name: create docker image
    command: docker build /opt/docker -t regapp:latest 

  - name: create tag to push image onto dockerhub
    command: docker tag regapp:latest muzkhan/tomcat:regapp

  - name: push docker image
    command: docker push muzkhan/tomcat:regapp
