apiVersion: v1
kind: Service
metadata:
  name: regapp-service
  labels:
    app: regapp

spec:
  type: LoadBalancer
  selector:
    app: regapp  # To which deployment should it sent traffic, Match the deployment label


  ports:
    - port: 8080  # service port
      targetPort: 8080

  

